version: '3'

services:
  mariadb:
    image: mariadb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8100:8080
    environment:
      ADMINER_PLUGINS: mongo mongodb
    networks:
      - mynetwork

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=persona_db
    volumes:
      - ./data:/data/db
    networks:
      - mynetwork
    command: mongod --bind_ip_all --noauth
networks:
  mynetwork:
